tracer.property: "I am the dev"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://10.139.12.171/infinite?useSSL=false&useUnicode=true&amp&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC"
spring.datasource.username: "bdoc"
spring.datasource.password: "1qw2!@QW@"